### ISSUE TITLE
Boundary loss

### ISSUE THREAD

**Issue by ngoc-nguyen-0** [xuxiangsun/ST-Data#4]
Hi,
Could you please share the code to compute the boundary loss (figure 2, main paper)? Thank you very much!
Best,
Ngoc

**Comment by xuxiangsun** [comment]
Hi, Ngoc
Thank you for your interest in this work. We have submitted an extended version of this paper, and our code will be published as soon as the extended version of this paper is accepted.

Best,
Xuxiang

**Comment by ngoc-nguyen-0** [comment]
Hi Xuxiang,

If possible,  can you explain how to compute boundary loss (figure 2, main paper)? 
I want to implement it for my experiments. Thanks!

Best,
Ngoc

**Comment by xuxiangsun** [comment]
Hi, Ngoc


Could you please give me your email address? I could send you the code of boundary loss.


Best,
Xuxiang






                       
Original
                       
                     

From:"Ngoc Nguyen"< ***@***.*** &gt;;

Date:2023/5/11 10:43

To:"xuxiangsun/ST-Data"< ***@***.*** &gt;;

CC:"xuxiangsun"< ***@***.*** &gt;;"State change"< ***@***.*** &gt;;

Subject:Re: [xuxiangsun/ST-Data] Boundary loss (Issue #4)




 
Hi Xuxiang,
 
If possible,  can you explain how to compute boundary loss (figure 2, main paper)?
 I want to implement it for my experiments. Thanks!
 
Best,
 Ngoc

**Comment by ngoc-nguyen-0** [comment]
Hi Xuxiang,

Yes, please send the code via this email: ***@***.*** Thank you
very much!

Best,
Ngoc
